# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- refs/tags/*
- refs/heads/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: set
  displayName: Show Variables

- task: PowerShell@2
  displayName: Set git variables
  env:
    BUILD_BUILDNUMBER: $(Build.BuildNumber)
    BUILD_SOURCEBRANCHNAME: $(Build.SourceBranchName)
  inputs:
    targetType: inline
    script: |
      $var = "$(git describe --tags --always)".Trim()
      $ver = [Version]"0.0.0"
      if (!$var.Contains("."))
      {
        $var = "0.0.0-$var"
      }
      if ($var.Contains("-"))
      {
        $semver = "ci-$env:BUILD_BUILDNUMBER".Replace('.', '-')
        Write-Host "$("##vso[task.setvariable variable=VersionSuffix]")$semver"
        $ver = [Version]$var.Substring(0, $var.IndexOf('-'))
        $ver = [Version]"$($ver.Major).$($ver.Minor).$($ver.Build+1)"
        $verFromFile = [Version] [System.IO.File]::ReadAllText("version.txt")
        if ($ver.Major -ne $verFromFile.Major)
        {
          $ver = [Version]"$($verFromFile.Major).$($verFromFile.Minor)"
        }
      }
      else
      {
        $ver = [Version]$var
      }
      echo "Branch = $env:BUILD_SOURCEBRANCHNAME"
      echo "VersionPrefix = '$ver'"
      echo "VersionSuffix = '$semver'"
      Write-Host "$("##vso[task.setvariable variable=VersionPrefix]")$ver"

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=4.9.0'

- task: NuGetCommand@2
  displayName: Restore nuget packages
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: '**\bin\Release\**\Test.exe'
